### ISSUE TITLE
no output file for snpMLST.py genotype

### ISSUE THREAD

**Issue by snayfach** [snayfach/snpMLST-issues#10]
I ran this:  
`snpMLST.py genotype --db example/array/test-snp-kmers.json -1 unit_test/hts_reads/SRR413665_2.fastq.gz --out example/test.genotype`

But there was no output:
```
$ ls example/test.genotype
ls: example/test.genotype: No such file or directory
$ ls example/
array			haplotypes		snps_from_genomes
```

**Comment by zjshi** [comment]
I am on this issue, and will get it back you later

**Comment by snayfach** [comment]
Any updates on this?

**Comment by zjshi** [comment]
Hi Stephen, I am still on it. It turns out to be a tricky bug due to oversized buffer preassigned for output. When the output size is smaller than the buffer size,  a lot of null chars were written to output , which was mis-read by the succedent python script

**Comment by zjshi** [comment]
I just got the bug fixed, please also test it in your environment. Also, we may need open another issue for deciding the output format for the genotyping module.

**Comment by snayfach** [comment]
I will take a look, my first intuition is to use VCF format

**Comment by snayfach** [comment]
Hi Jason,

I reran the module using the command:
```
snpMLST.py genotype --db example/array/test-snp-kmers.json -1 unit_test/hts_reads/SRR413665_2.fastq.gz --out example/test.genotype
```

The output file looked like this:
```
#BEGIN
#END
```

What does the output file look like when you run the same command? I used the test data in the unit test directory to create the database and for the short reads:

```
GENOMES=unit_test/midas_genomes/Borrelia_burgdorferi_56121
snpMLST.py snps genomes --fna-dir $GENOMES --out-dir example/snps_from_genomes --threads 10
```

```
INDIR=example/snps_from_genomes
snpMLST.py haplotypes --fna $INDIR/consensus.fna --vcf $INDIR/core_snps.vcf --coords $INDIR/coords.tsv -o example/haplotypes
```

```
INDIR=example/snps_from_genomes
snpMLST.py array --snp-clusters example/haplotypes --core-genome $INDIR/consensus.fna --coords $INDIR/coords.tsv --genome-name test --out example/array
```

Thanks,
Stephen

**Comment by zjshi** [comment]
I think it might caused by the an empty result. In the most updated repo, I shorten the kmers to 13 bases for sake of testing. So would you please re-run the previous step with the following command:

> snpMLST.py array --snp-clusters ./snps_from_genomes/Borrelia_burgdorferi_56121/snps_dump.json --core-genome ./snps_from_genomes/Borrelia_burgdorferi_56121/consensus.fna --coords ./snps_from_genomes/Borrelia_burgdorferi_56121/coords.tsv --out ./          snps_from_genomes/Borrelia_burgdorferi_56121/build_db_exp1 --overwrite -k 13

then run the genotype command line? It should give non-empty output.

**Comment by zjshi** [comment]
Code blocked version:
`snpMLST.py array --snp-clusters ./snps_from_genomes/Borrelia_burgdorferi_56121/snps_dump.json --core-genome ./snps_from_genomes/Borrelia_burgdorferi_56121/consensus.fna --coords ./snps_from_genomes/Borrelia_burgdorferi_56121/coords.tsv --out ./ snps_from_genomes/Borrelia_burgdorferi_56121/build_db_exp1 --overwrite -k 13`

**Comment by zjshi** [comment]
code blocked version:
`snpMLST.py array --snp-clusters ./snps_from_genomes/Borrelia_burgdorferi_56121/snps_dump.json --core-genome ./snps_from_genomes/Borrelia_burgdorferi_56121/consensus.fna --coords ./snps_from_genomes/Borrelia_burgdorferi_56121/coords.tsv --out ./ snps_from_genomes/Borrelia_burgdorferi_56121/build_db_exp1 --overwrite -k 13`

**Comment by snayfach** [comment]
Worked!
