### ISSUE TITLE
Defining AF in snps module

### ISSUE THREAD

**Issue by snayfach** [snayfach/snpMLST-issues#11]
This issue is a bit tricky.

First we need to decide on a definition for AF. Our options are:
1) Frequency of the reference allele
2) Frequency of the alternate allele
3) Frequency of the minor allele

The current definition of AF is the third one. Based on this definition, the pooled AF (based on all samples) should never go above 0.50. But you can see that it DOES:
`grep AF=1.0 example/snps_from_genomes/core_snps.vcf | less`

The other problem, is that there is no field for specifying the minor allele in the VCF spec. So from looking at the VCF now, there's no way to tell what allele is being referred to by AF. Sometimes it will be the reference allele; other times it will be the alternate allele. Our options are:
1) Change the definition of AF to (1) or (2) above and specify the definition in the VCF header `##INFO=<ID=AF,Number=A,Type=Float,Description="Reference|Alternate Allele Frequency">`
2) Specify the minor allele in the info field:
```
##INFO=<ID=MA,...,Description="Minor Allele">`
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT 498736.3.fna.ref 139.81.fna 224326.49.fna 445983.22.fna 498737.3.fna 498740.12.fna 521008.3.fna
cluster53       294     843     T       C       .       PASS    NS=7;DP=7;AF=0.143,MA=C
```

For the first issue, I suggest we adopt (2)
For the second issue, I suggest we adopt (1)

Let me know if this makes sense.

Thanks,
Stephen

**Comment by zjshi** [comment]
I agree with the choices you suggested, and I will be update the code to reflect the changes.
