### ISSUE TITLE
#!/usr/bin/env python2

### ISSUE THREAD

**Issue by snayfach** [snayfach/snpMLST-issues#2]
Hey @zjshi,

You need to change `#!/usr/bin/env python2` to `#!/usr/bin/env python` in your code

======================================================================
FAIL: test_class (__main__._11_RunArrayMetagenome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./snpMLST_test.py", line 196, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: env: python2: No such file or directory

**Comment by zjshi** [comment]
done!
