### ISSUE TITLE
Create .gitignore file

### ISSUE THREAD

**Issue by snayfach** [snayfach/snpMLST-issues#3]
Hey @zjshi,

You need to create a `.gitignore` to list files and directories that should not be tracked in the repo. Lots of temp files are being tracked in the test dir

**Comment by zjshi** [comment]
I was not about this issue, since there is  a .gitignore file (https://github.com/zjshi/snpMLST/blob/master/.gitignore) to exclude the test dir. Are you still seeing the test dir?

**Comment by snayfach** [comment]
Oh, I see it now. Thanks! 

* you may want to add other test files like 'master.sh' and 'test_with_ids.log'
* .pyc should be removed and untracked at some point
* .bak files are deprecated and can be removed

**Comment by zjshi** [comment]
Got it, they should be gone now.

**Comment by zjshi** [comment]
Do you still see the temporary files?

**Comment by snayfach** [comment]
Looks like you got them, thanks! I do see .DS_Store, snp_mlst/.DS_Store which can be removed
