### ISSUE TITLE
snpMLST.py snps genomes --snp-freq 0.0

### ISSUE THREAD

**Issue by snayfach** [snayfach/snpMLST-issues#4]
Bug when specifying `snpMLST.py snps genomes --snp-freq 0.0`. This should give identical results to running `snpMLST.py snps genomes`. Please see what is happening and double check that the default value for --snp-freq is 0.0 as indicated from the help text:

```
snp-calling:
  --max-sites INT   Maximum genomic sites to parse (use all); useful for testing
  --min-prev FLOAT  Minimum prevalence (1.0)
  --snp-freq FLOAT  Minimum minor allele frequency for SNP calling (0.0)
```

**Comment by zjshi** [comment]
fixed by setting default from 0.0 to 0.01
