### ISSUE TITLE
NS, DP, and AF not calculated properly in presence of missing data

### ISSUE THREAD

**Issue by snayfach** [snayfach/snpMLST-issues#6]
When there is missing data, NS, DP, and AF are not calculated properly in presence of missing data. For an example, see any rows where the AF=None for 1 or more samples

**Comment by zjshi** [comment]
Is this for "snps reads"?

**Comment by snayfach** [comment]
For both snps reads and snps genomes I think

**Comment by snayfach** [comment]
Hmmmm, this looks fixed now. Did you change anything?

**Comment by zjshi** [comment]
Not really, but maybe it is due to some obsolete code before the update.

**Comment by snayfach** [comment]
OK. Closing for now but will reopen if the issue reappears
