### ISSUE TITLE
print summary statistics in snpMLST.py haplotypes

### ISSUE THREAD

**Issue by snayfach** [snayfach/snpMLST-issues#8]
At the end of the module, please print the number of SNPs and the number of haplotypes; useful information to report to use

**Comment by zjshi** [comment]
changes have been made

**Comment by snayfach** [comment]
I'm a bit confused on the #s being reported. 

My VCF file contains 13882 SNPs:
```
$ grep -c -v '#' example/snps_from_genomes/core_snps.vcf
13882
```

However the haplotypes module only reports 9445 SNPs. Where are the rest of them? 
```
[id-loci] Identifying core-genome loci
	100% complete, 0.0s min left, 3711.98 sites/sec
	total snp blocks: 9445
	total length: 171233
	total snps: 13882
	elapsed seconds: 3.75
```

Also it says they were clustered into 33 haplotype blocks. Is that really true?

```
[cluster-loci] Clustering loci by r2
[divide r2 matrix] divide the R2 matrix into submatrices based on the minimum R2 value
	elapsed seconds: 1.15
	number of groups of snp blocks: 33
	count locus groups: 33
	elapsed seconds: 1.46
```

**Comment by zjshi** [comment]
let me please double check it

**Comment by zjshi** [comment]
Double checked, just send you an email including the result

**Comment by snayfach** [comment]
Thanks for checking - glad everything is working! Does that mean all 13,882 SNPs are present in one of the 33 clusters? I'm interested to know how many SNPs are being clustered together (i.e. what is the data reduction).

Thanks,
Stephen

**Comment by zjshi** [comment]
I am not sure I understand, but in the file I sent you there should be 33 block groups (0-32). Clusters (e.g. cluster54 in Block group 0) is the name of 'chrom'.
For example:
> Block group 0
>     cluster54:294 [tag]
>         cluster54:294 [member]: 0.0-0.0-0.0-0.0-1.0-0.0-0.0
>     cluster58:18931 [tag]
>         cluster58:18931 [member]: 0.0-0.0-0.0-0.0-1.0-0.0-0.0
>         cluster58:18990 [member]: 0.0-0.0-0.0-0.0-1.0-0.0-0.0
above shows a block group 0, which has two snp blocks (the first one has 1 member snp, the second one has two members) labeled by their tag snps. Sorry for the resulted confusion, let me know if some places are not clear.

**Comment by snayfach** [comment]
This is helpful, thank you. Does this mean than the SNPs in Block group 0 are all in LD (r2 > 0.95)?

**Comment by zjshi** [comment]
Sure! The implementation in the current repo is to partition global correlation matrix between tag SNPs in a greedy fashion. The algorithm starts from the first tag snp, then attach all other tag snps to it if r2 > 0.95, then the algorithm move to the next available snp (those didn't attach to the first one), and so on so forth.

**Comment by snayfach** [comment]
OK, great this is clear to me now. Thank you
